#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## functions for manager panel
##--------------------------------------------------
panel_link("nfsshare", "manager");



foreach (qw(sysconfig/nfs exports))
{
    templates2events("/etc/$_", qw(
	console-save
	bootstrap-console-save
	remoteaccess-update
        nfs-update
    ));
}

foreach $event (qw(remoteaccess-update nfs-update))
{
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nfs");
}

service_link_enhanced("rpcbind", "S13", "7");
service_link_enhanced("nfslock", "S59", "7");
service_link_enhanced("nfs", "S60", "7");
